---
name: Spotify Connect
version: dev
slug: spotify
description: Play Spotify music on your Home Assistant device (with normalization)
url: https://github.com/mehmet-efe61/addon-spotify-connect
arch:
  - aarch64
  - amd64
  - armv7
host_network: true
audio: true
init: false
options:
  name: Home Assistant
  bitrate: 160
  initial_volume: 50
  autoplay: true
  enable_volume_normalisation: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  username: str?
  password: password?
  autoplay: bool
  enable_volume_normalisation: bool
  initial_volume: match(^([0-9]|[1-9][0-9]|100)$)?
